TODO :

* 12/14/16:
	* Client Log function
	* Kernel manager (restart dead kernel ?)
	* Fix bug : for ndarray savetxt : IndexError: list index out of range
	* Daemon : Fix some bugs
	* Kernel options (extra_arguments=["--matplotlib='inline'"])
	* Fix lockfile creation
	* Compatibility python 3.x :
	    * print : **ok**
	    * dict.keys() : **ok**
	    * import : to check
 	    * from io import open : to check
	    * class myclass(object) : to check
